[workspace]
members = ["baumstamm-lib", "baumstamm-tauri", "baumstamm-cli"]

[workspace.package]
description = "Baumstamm - Stammbäume erstellen"
authors = ["Alec Ghost"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.63"
