[package]
name = "baumstamm-grid"
version = "0.2.0"
authors = ["Alec Ghost"]
license = "Apache-2.0"
repository = "https://github.com/AlecGhost/baumstamm"
edition.workspace = true
rust-version.workspace = true

[dependencies]
baumstamm-lib = { path = "../baumstamm-lib" }
serde = { version = "1.0.229", features = ["derive"] }
specta = "1.0.5"
itertools = "0.15.0"
